import React from "react";
import { Layout } from "@/components/layout";
import { FileText, ShieldAlert } from "lucide-react";

export default function Protocol() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-4 py-8 sm:py-12">
        <div className="mb-8 sm:mb-12">
          <h1 className="text-2xl sm:text-3xl font-serif text-primary tracking-tight mb-3 flex items-center gap-2 sm:gap-3">
            <FileText className="w-6 h-6 sm:w-8 sm:h-8 flex-shrink-0" />
            Silent Witness Protocol
          </h1>
          <p className="text-base sm:text-lg text-muted-foreground">
            Version 0.1 Draft Specifications
          </p>
        </div>

        <div className="prose prose-slate max-w-none text-foreground prose-headings:font-serif prose-headings:text-primary prose-sm sm:prose-base">
          <div className="bg-muted border-l-4 border-destructive p-4 sm:p-6 mb-6 sm:mb-8 text-sm not-prose">
            <h4 className="flex items-start gap-2 text-destructive mt-0 mb-2 font-semibold">
              <ShieldAlert className="w-5 h-5 flex-shrink-0 mt-0.5" />
              Important Warning
            </h4>
            <p className="mb-0 text-muted-foreground text-xs sm:text-sm leading-relaxed">
              Silent Witness may help show that a matching file, text, or evidence package
              existed before a recorded time. It does not prove that an event happened,
              identify a perpetrator, or guarantee legal admissibility.
            </p>
          </div>

          <h2>What Silent Witness is</h2>
          <p>
            Silent Witness is a cryptographic timestamping mechanism designed to allow
            individuals in high-risk situations to create a verifiable record of digital
            evidence without transmitting the actual evidence across a network or storing
            it on third-party servers.
          </p>

          <h2>What problem it solves</h2>
          <p>
            Uploading sensitive videos, images, or testimonies often puts the uploader at
            immediate physical or legal risk. However, holding onto the evidence without
            establishing a timeline can lead to accusations of fabrication after the fact.
            Silent Witness bridges this gap by recording possession of the data at a
            specific time without revealing the data itself.
          </p>

          <h2>Design principles</h2>
          <ul>
            <li>
              <strong>Local First:</strong> The evidence never leaves the device. All
              processing occurs in the browser memory.
            </li>
            <li>
              <strong>Cryptographic Certainty:</strong> Uses standard SHA-256 hashing to
              ensure any modification to the original file will result in a completely
              different fingerprint.
            </li>
            <li>
              <strong>Minimal Disclosure:</strong> Public records contain only safe
              metadata (e.g., file sizes, approximate locations, general event types) to
              protect the identity and exact location of the witness.
            </li>
            <li>
              <strong>No Precise Maps:</strong> No maps, GPS coordinates, or street-level
              data are accepted or stored in this version. Only country, region, and city
              fields are allowed, and all are user-provided manually.
            </li>
            <li>
              <strong>Automatic Policy:</strong> Publication decisions are made by
              server-side rules, not by a human reviewer. Records that pass all checks
              appear immediately in the public registry.
            </li>
          </ul>

          <h2>What a witness record contains</h2>
          <p>A witness record (or manifest) is a JSON document containing:</p>
          <ul>
            <li>Protocol version identifiers.</li>
            <li>The cryptographic hashes of one or more files.</li>
            <li>A top-level package hash representing the entire manifest.</li>
            <li>
              Safe descriptor metadata (e.g., duration buckets, size buckets, whether
              GPS data exists).
            </li>
            <li>A generalized public context (country, region, event type).</li>
          </ul>

          <h2>Timestamps</h2>
          <p>Every public record carries two separate timestamps:</p>
          <ul>
            <li>
              <strong>createdAtLocal</strong> — generated by the user's browser at
              fingerprint creation time. Comes from the device clock. Not independently
              verified. Stored as provided. Displayed with a warning.
            </li>
            <li>
              <strong>serverReceivedAtUtc</strong> — set exclusively by the server when
              the submission is received. The frontend cannot set or override this value.
              It proves only that the registry received the fingerprint by that time.
            </li>
          </ul>

          <h2>What it proves</h2>
          <p>
            A registry timestamp proves only that this fingerprint was submitted to the
            registry no later than that server time. It does not prove when the original
            file was created and does not prove that the event happened.
          </p>
          <p>
            If someone later presents a file that generates the exact same hash, it is
            mathematically certain they are the same file.
          </p>

          <h2>What it does not prove</h2>
          <p>
            It does not prove the contents of the file are true, unedited prior to
            hashing, or correctly described. It does not prove that an event happened,
            identify a perpetrator, or constitute legal certification of any kind.
          </p>

          <h2>Publication status vocabulary</h2>
          <p>
            Each public record carries one of the following publication status values.
            Only <code>accepted_public</code> and <code>exact_match_published</code> records
            appear in the public registry.
          </p>
          <ul>
            <li>
              <strong>accepted_public</strong> — The fingerprint passed all automatic
              policy checks and is immediately visible in the public registry. No human
              reviewer is involved.
            </li>
            <li>
              <strong>rejected_by_policy</strong> — The submission failed an automatic
              safety or quality check. It is never stored or shown publicly.
            </li>
            <li>
              <strong>retracted_by_holder</strong> — The holder used their retraction
              token to remove the record from public view.
            </li>
            <li>
              <strong>exact_match_published</strong> — A later file was verified as
              byte-for-byte identical to this fingerprint.
            </li>
          </ul>

          <h2>Automatic publication policy</h2>
          <p>
            Records are published automatically if they pass all of the following
            server-side checks:
          </p>
          <ul>
            <li>
              <strong>Quality level:</strong> Must be A, B, or C. Quality D records are
              rejected. See <em>Quality levels</em> below.
            </li>
            <li>
              <strong>Location field safety:</strong> Country, region, and city fields
              must not contain phone numbers, GPS coordinates, URLs, email addresses,
              street addresses, vehicle plate patterns, or violent language.
            </li>
            <li>
              <strong>Duplicate check:</strong> A duplicate package hash returns an error
              with a link to the existing public record.
            </li>
            <li>
              <strong>Rate limit:</strong> A maximum of 10 submissions per IP address
              per hour.
            </li>
          </ul>

          <h2>Privacy rules</h2>
          <p>
            Witnesses are instructed to withhold details that could identify them or the
            subjects of the evidence unless they intend to publish it fully. Location
            fields must not contain phone numbers, exact addresses, vehicle registration
            plates, full names, or direct accusations — these are automatically rejected
            by the server.
          </p>

          <h2>Geographic safety rules</h2>
          <p>
            Coordinates are intentionally excluded. The system detects if GPS metadata
            exists in a file but records only a boolean flag ("present" or "absent")
            rather than the coordinates themselves. No maps or precise locations are
            shown in this version.
          </p>

          <h2>Quality levels and public registry</h2>
          <p>
            Records are assigned a quality level (A, B, or C) based on completeness.
            Quality D records are automatically rejected from the public registry.
            They may still be saved locally as proof packages.
          </p>
          <ul>
            <li><strong>A</strong> — Known event type + known evidence type + descriptor</li>
            <li><strong>B</strong> — One of event type or evidence type known + descriptor</li>
            <li><strong>C</strong> — Minimal — event and evidence type only, no descriptor</li>
            <li><strong>D</strong> — Both event type and evidence type withheld with no descriptor — rejected</li>
          </ul>

          <h2>Spam and false-claim handling</h2>
          <p>
            Because the registry accepts unverified hashes, spam is possible. The
            registry's automatic policy (quality grading, rate limiting, and location
            field validation) reduces low-effort spam. Quality D records are rejected
            outright. Investigators and research teams are responsible for secondary
            corroboration using the original file and contextual knowledge.
          </p>

          <h2>Safe evidence descriptor</h2>
          <p>
            To assist researchers in matching later disclosed files with earlier
            fingerprints, the protocol attaches bucketed metadata (e.g., "Video,
            1–5min, medium file size"). This makes it easier to correlate without
            revealing too much.
          </p>

          <h2>Verification process</h2>
          <p>
            An investigator holding a raw file can run it through the Verification tool
            to generate its local hash and compare it against registry hashes to find a
            match.
          </p>

          <h2>Public wording rules</h2>
          <p>When citing Silent Witness records, the following terminology must be used:</p>
          <ul>
            <li>
              <strong>Use:</strong> "Timestamped fingerprint", "Original evidence not
              published", "Not independently verified", "Can be checked later if the
              original is provided".
            </li>
            <li>
              <strong>Do not use:</strong> "Verified kidnapping", "Proven crime",
              "Authenticated by Silent Witness", "Legal proof", "Legally sufficient".
            </li>
          </ul>

          <h2>Future anchoring note</h2>
          <p>
            Future versions may anchor daily Merkle roots to OpenTimestamps or public
            chains. This MVP does not perform blockchain anchoring. Currently, the
            registry timestamp relies on the server's receipt time only.
          </p>
        </div>
      </div>
    </Layout>
  );
}
