import React from "react";
import { Layout } from "@/components/layout";
import { FileText, ShieldAlert } from "lucide-react";

export default function Protocol() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-4 py-8 sm:py-12">
        <div className="mb-8 sm:mb-12">
          <h1 className="text-2xl sm:text-3xl font-serif text-primary tracking-tight mb-3 flex items-center gap-2 sm:gap-3">
            <FileText className="w-6 h-6 sm:w-8 sm:h-8 flex-shrink-0" />
            Silent Witness Protocol
          </h1>
          <p className="text-base sm:text-lg text-muted-foreground">
            Version 0.1 Draft Specifications
          </p>
        </div>

        <div className="prose prose-slate max-w-none text-foreground prose-headings:font-serif prose-headings:text-primary prose-sm sm:prose-base">
          <div className="bg-muted border-l-4 border-destructive p-4 sm:p-6 mb-6 sm:mb-8 text-sm not-prose">
            <h4 className="flex items-start gap-2 text-destructive mt-0 mb-2 font-semibold">
              <ShieldAlert className="w-5 h-5 flex-shrink-0 mt-0.5" />
              Important Warning
            </h4>
            <p className="mb-0 text-muted-foreground text-xs sm:text-sm leading-relaxed">
              Silent Witness may help show that a matching file, text, or evidence package
              existed before a recorded time. It does not prove that an event happened,
              identify a perpetrator, or guarantee legal admissibility.
            </p>
          </div>

          <h2>What Silent Witness is</h2>
          <p>
            Silent Witness is a cryptographic timestamping mechanism designed to allow
            individuals in high-risk situations to create a verifiable record of digital
            evidence without transmitting the actual evidence across a network or storing
            it on third-party servers.
          </p>

          <h2>What problem it solves</h2>
          <p>
            Uploading sensitive videos, images, or testimonies often puts the uploader at
            immediate physical or legal risk. However, holding onto the evidence without
            establishing a timeline can lead to accusations of fabrication after the fact.
            Silent Witness bridges this gap by recording possession of the data at a
            specific time without revealing the data itself.
          </p>

          <h2>Design principles</h2>
          <ul>
            <li>
              <strong>Local First:</strong> The evidence never leaves the device. All
              processing occurs in the browser memory.
            </li>
            <li>
              <strong>Cryptographic Certainty:</strong> Uses standard SHA-256 hashing to
              ensure any modification to the original file will result in a completely
              different fingerprint.
            </li>
            <li>
              <strong>Minimal Disclosure:</strong> Public records contain only safe
              metadata (e.g., file sizes, approximate locations, general event types) to
              protect the identity and exact location of the witness.
            </li>
            <li>
              <strong>No Precise Maps:</strong> No maps, GPS coordinates, or street-level
              data are accepted or stored in this version. Only country, region, and city
              fields are allowed, and all are user-provided manually.
            </li>
          </ul>

          <h2>What a witness record contains</h2>
          <p>A witness record (or manifest) is a JSON document containing:</p>
          <ul>
            <li>Protocol version identifiers.</li>
            <li>The cryptographic hashes of one or more files.</li>
            <li>A top-level package hash representing the entire manifest.</li>
            <li>
              Safe descriptor metadata (e.g., duration buckets, size buckets, whether
              GPS data exists).
            </li>
            <li>A generalized public context (Country, Region, Event Type).</li>
          </ul>

          <h2>Timestamps</h2>
          <p>Every public record carries two separate timestamps:</p>
          <ul>
            <li>
              <strong>createdAtLocal</strong> — generated by the user's browser at
              fingerprint creation time. Comes from the device clock. Not independently
              verified. Stored as provided.
            </li>
            <li>
              <strong>serverReceivedAtUtc</strong> — set exclusively by the server when
              the submission is received. The frontend cannot set or override this value.
              It proves only that the registry received the fingerprint by that time.
            </li>
          </ul>

          <h2>What it proves</h2>
          <p>
            A registry timestamp proves only that this fingerprint was submitted to the
            registry no later than that server time. It does not prove when the original
            file was created and does not prove that the event happened.
          </p>
          <p>
            If someone later presents a file that generates the exact same hash, it is
            mathematically certain they are the same file.
          </p>

          <h2>What it does not prove</h2>
          <p>
            It does not prove the contents of the file are true, unedited prior to
            hashing, or correctly described. It does not prove that an event happened,
            identify a perpetrator, or constitute legal certification of any kind.
          </p>

          <h2>Record status vocabulary</h2>
          <p>
            Each public record carries one of the following status values:
          </p>
          <ul>
            <li>
              <strong>timestamped_only_not_verified</strong> — Default for all submitted
              records. The registry received the fingerprint; no external review has
              occurred.
            </li>
            <li>
              <strong>exact_match_published</strong> — A verified partner confirmed an
              original file matches this fingerprint.
            </li>
            <li>
              <strong>not_matching</strong> — A presented file does not match the stored
              fingerprint.
            </li>
            <li>
              <strong>externally_reviewed</strong> — A trusted organisation has reviewed
              and annotated the record.
            </li>
          </ul>
          <p>
            All records submitted through the public form default to
            <code>timestamped_only_not_verified</code>.
          </p>

          <h2>Privacy rules</h2>
          <p>
            Witnesses are instructed to withhold details that could identify them or the
            subjects of the evidence unless they intend to publish it fully. Public notes
            must not contain phone numbers, exact addresses, vehicle registration plates,
            full names, or direct accusations.
          </p>

          <h2>Geographic safety rules</h2>
          <p>
            Coordinates are intentionally excluded. The system detects if GPS metadata
            exists in a file but records only a boolean flag ("present" or "absent")
            rather than the coordinates themselves. No maps or precise locations are
            shown in this version.
          </p>

          <h2>Quality levels and public registry</h2>
          <p>
            Records are assigned a quality level (A, B, or C) based on completeness.
            Quality D records are rejected from the public registry with a clear message.
            They may still be saved locally as proof packages.
          </p>

          <h2>Spam and false-claim handling</h2>
          <p>
            Because the registry accepts unverified hashes, spam is possible. The
            registry relies on investigative journalists and human rights organisations
            to maintain secondary verified lists of hashes that correspond to actual
            verified events.
          </p>

          <h2>Safe evidence descriptor</h2>
          <p>
            To assist researchers in matching later disclosed files with earlier
            fingerprints, the protocol attaches bucketed metadata (e.g., "Video,
            1–5min, medium file size"). This makes it easier to correlate without
            revealing too much.
          </p>

          <h2>Verification process</h2>
          <p>
            An investigator holding a raw file can run it through the Verification tool
            to generate its local hash and compare it against registry hashes to find a
            match.
          </p>

          <h2>Public wording rules</h2>
          <p>When citing Silent Witness records, the following terminology must be used:</p>
          <ul>
            <li>
              <strong>Use:</strong> "Timestamped fingerprint", "Original evidence not
              published", "Not publicly verified", "Can be checked later if the original
              is provided".
            </li>
            <li>
              <strong>Do not use:</strong> "Verified kidnapping", "Proven crime",
              "Authenticated by Silent Witness", "Legal proof", "Legally sufficient".
            </li>
          </ul>

          <h2>Future anchoring note</h2>
          <p>
            Future versions may anchor daily Merkle roots to OpenTimestamps or public
            chains. This MVP does not perform blockchain anchoring. Currently, the
            registry timestamp relies on the server's receipt time only.
          </p>
        </div>
      </div>
    </Layout>
  );
}
